//Auth
export const SET_AUTH_STATUS = 'SET_AUTH_STATUS';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_USER = 'SET_USER';

//flowchart
export const ADD_FLOW_COMPONENT = 'ADD_FLOW_COMPONENT';
export const SET_POSITION = 'SET_POSITION';
export const SET_COMPONENT = 'SET_COMPONENT';
export const SET_UNSELECT = 'SET_UNSELECT';
export const SET_SELECTED_COMPONENT = 'SET_SELECTED_COMPONENT';
export const SET_COMPONENTS = 'SET_COMPONENTS';
export const SET_FLOWCHART_OUTPUT = 'SET_FLOWCHART_OUTPUT';
export const SET_FLOWCHART_STATUS = 'SET_FLOWCHART_STATUS';
export const SET_MOVE_COMPONENT = 'SET_MOVE_COMPONENT';
export const SET_SELECT = 'SET_SELECT';
export const SET_CONNECTED_COMPONENTS = 'SET_CONNECTED_COMPONENTS';
export const SET_CREATED_COMPONENTS = 'SET_CREATED_COMPONENTS';
export const SET_CONNECT = 'SET_CONNECT';
export const SET_EXPORT_SRC = 'SET_EXPORT_SRC';